version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'vet-clinic'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - backend
  vet-clinic:
    build: ./
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - DATASOURCE_URL=jdbc:mysql://db:3306/vet-clinic
    networks:
      - backend
networks:
  backend: 